CivCloudBot:
    logLevel: 20 #20 = logLevel INFO, use 10 for DEBUG
    #replace the base url with the URL of your host
    BaseURL: http://example.org
    
    WebHookReceiver:
        ip: '' #blank string to listen on all interfaces
        port: 80
    
    Bots:
        Telegram:
            #add your Telegram Bot Api Key here
            ApiKey: changeit
          
    
