version: "3.3"
services:
  civbot:
    build: .
    ports: 
     - 80:80
    environment:
     #add your Telegram Bot Api Key here
     - CivCloudBot_Bots_Telegram_ApiKey=changeit!
     #change to your BaseURL
     - CivCloudBot_BaseURL=http://example.de
     - CivCloudBot_MongoDB_host=mongo
     #all other configuration variables defined in the configuration.yaml 
     #can also be overwritten here by adding more environment variables
    links:
     - mongo:mongo
  mongo:
    image: ivanmarban/armhf-mongodb
    volumes:
     - ./mongodata:/var/lib/mongodb
    ports:
     - 27017:27017
